### ISSUE TITLE
Forcefield extension creates ghost blocks for other players

### ISSUE THREAD

**Issue by Animationking11** [SirBlobman/CombatLogX#453] opened 2022-07-07 05:43 UTC
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

When a player gets tagged in combat and they place a block on the red glass (or whatever block it is in config) it will make a ghost block for the other players online

### Reproduction Steps

Install and setup the forcefield extension
Get 2 accounts online
With one account tag yourself in combat near a protected area
then when you see the border place blocks on it
then on your other account if they where in reader distance of the border they will see ghost blocks

### Expected behaviour

You see ghost blocks

### Screenshots / Videos

I am on a really bad computer right now but if you need more info please reply to the thread I am active on github

### CombatLogX Version

07.07 05:43:15 [Server] INFO Java Version: 17
07.07 05:43:15 [Server] INFO Java Vendor: AdoptOpenJDK
07.07 05:43:15 [Server] INFO Server Version: git-Paper-"e4f5e1c" (MC: 1.19)
07.07 05:43:15 [Server] INFO Bukkit Version: 1.19-R0.1-SNAPSHOT
07.07 05:43:15 [Server] INFO Minecraft Version: 1.19
07.07 05:43:15 [Server] INFO NMS Version: 1_19_R1
07.07 05:43:15 [Server] INFO Dependency Information:
07.07 05:43:15 [Server] INFO - SirBlobmanCore v2.4.0-Dev
07.07 05:43:15 [Server] INFO - Essentials v2.19.5-dev+22-9c5536b
07.07 05:43:15 [Server] INFO - PlaceholderAPI v2.11.1
07.07 05:43:15 [Server] INFO - ProtocolLib v5.0.0-SNAPSHOT-b570
07.07 05:43:15 [Server] INFO - WorldGuard v7.0.7+216b061
07.07 05:43:15 [Server] INFO CombatLogX by SirBlobman
07.07 05:43:15 [Server] INFO Plugin Version: 11.0.0.0-Beta-778
07.07 05:43:15 [Server] INFO Spigot Version: 10.4.2.4
07.07 05:43:15 [Server] INFO Enabled Expansions (7):
07.07 05:43:15 [Server] INFO - ActionBar
07.07 05:43:15 [Server] INFO - CheatPrevention
07.07 05:43:15 [Server] INFO - CompatWorldGuard
07.07 05:43:15 [Server] INFO - DeathEffects
07.07 05:43:15 [Server] INFO - ForceField
07.07 05:43:15 [Server] INFO - Logger
07.07 05:43:15 [Server] INFO - NewbieHelper

**Comment by SirBlobman** [comment] 2022-07-25 00:08
@Animationking11 Can you send a video of this happening on the newest version? The fake block packets should only be sent to the player that needs to see it.

**Comment by Animationking11** [comment] 2022-07-25 06:50
> @Animationking11 Can you send a video of this happening on the newest version? The fake block packets should only be sent to the player that needs to see it.

It does only get sent to the player but if they place a block onto those fake blocks the blocks stay even when they are not in combat anymore (As I said ghost blocks so the only one that sees those blocks is the one that was in combat and placing blocks on the wall) then they can jump on the glass and it looks like they are flying to other players because its a ghost block.

**Comment by Animationking11** [comment] 2022-07-25 07:00
Video of me making bug https://youtu.be/6-lm9JQfxI4

**Comment by SirBlobman** [comment] 2022-09-11 02:06
@Animationking11 does the bug still exist with the new build? [CombatLogX 984](https://jenkins.sirblobman.xyz/job/SirBlobman/job/CombatLogX/984/)

**Comment by SirBlobman** [comment] 2023-01-15 06:02
Closing due to no reply, reopen this if the issue is still occurring.

**Closed by SirBlobman** 2023-01-15 06:02 UTC
Labels: Bug
