### ISSUE TITLE
console eror 

### ISSUE THREAD

**Issue by successed** [SirBlobman/CombatLogX#67] opened 2019-02-11 06:54 UTC
[09:51:50 INFO]: [Savaşçı] Failed to load expansion:
[09:51:50 WARN]: java.lang.NoClassDefFoundError: me/angeschossen/lands/landsaddons/LandsAddon
[09:51:50 WARN]:        at com.SirBlobman.expansion.lands.utility.LandsUtil.getAddon(LandsUtil.java:19)
[09:51:50 WARN]:        at com.SirBlobman.expansion.lands.utility.LandsUtil.onDisable(LandsUtil.java:42)
[09:51:50 WARN]:        at com.SirBlobman.expansion.lands.CompatLands.disable(CompatLands.java:59)
[09:51:50 WARN]:        at com.SirBlobman.combatlogx.expansion.Expansions.unloadExpansion(Expansions.java:136)
[09:51:50 WARN]:        at com.SirBlobman.expansion.lands.CompatLands.enable(CompatLands.java:53)
[09:51:50 WARN]:        at com.SirBlobman.combatlogx.expansion.Expansions.loadExpansion(Expansions.java:50)
[09:51:50 WARN]:        at com.SirBlobman.combatlogx.expansion.Expansions.loadExpansions(Expansions.java:103)
[09:51:50 WARN]:        at com.SirBlobman.combatlogx.CombatLogX.lambda$onEnable$0(CombatLogX.java:50)
[09:51:50 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82)
[09:51:50 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449)
[09:51:50 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003)
[09:51:50 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[09:51:50 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938)
[09:51:50 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
[09:51:50 WARN]:        at java.lang.Thread.run(Thread.java:748)
[09:51:50 WARN]: Caused by: java.lang.ClassNotFoundException: me.angeschossen.lands.landsaddons.LandsAddon
[09:51:50 WARN]:        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[09:51:50 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:138)
[09:51:50 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:84)
[09:51:50 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[09:51:50 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[09:51:50 WARN]:        ... 15 more

**Comment by SirBlobman** [comment] 2019-02-11 10:50
Duplicate of #66

**Closed by SirBlobman** 2019-02-11 10:50 UTC
