### ISSUE TITLE
Console error 1.21.4

### ISSUE THREAD

**Issue by Remski01** [SirBlobman/CombatLogX#874] opened 2024-12-19 17:32 UTC
### Server Implementation

Paper

### Server Version

1.21, build: 15.

### Describe the bug

Error in console.

### Reproduction Steps

1. Hit an player.
2. hello error.

### Expected behaviour

No error.

### Screenshots / Videos

```
[18:20:34 ERROR]: Could not pass event PlayerTagEvent to CombatLogX v11.5.0.0.1242
java.lang.IncompatibleClassChangeError: Found interface org.bukkit.inventory.InventoryView, but class was expected
        at combatlogx.expansion.cheat.prevention.listener.ListenerInventories.onTag(ListenerInventories.java:29) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor658.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at CombatLogX.jar/com.github.sirblobman.combatlogx.manager.CombatManager.tag(CombatManager.java:108) ~[CombatLogX.jar:?]
        at CombatLogX.jar/com.github.sirblobman.combatlogx.manager.CombatManager.tag(CombatManager.java:65) ~[CombatLogX.jar:?]
        at CombatLogX.jar/com.github.sirblobman.combatlogx.listener.ListenerDamage.checkTag(ListenerDamage.java:134) ~[CombatLogX.jar:?]
        at CombatLogX.jar/com.github.sirblobman.combatlogx.listener.ListenerDamage.onDamage(ListenerDamage.java:44) ~[CombatLogX.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor629.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEvent(CraftEventFactory.java:276) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1207) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1197) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1127) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1090) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1251) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at net.minecraft.world.entity.LivingEntity.handleEntityDamage(LivingEntity.java:2432) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at net.minecraft.world.entity.LivingEntity.hurtServer(LivingEntity.java:1522) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at net.minecraft.world.entity.player.Player.hurtServer(Player.java:960) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at net.minecraft.server.level.ServerPlayer.hurtServer(ServerPlayer.java:1458) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at net.minecraft.world.entity.Entity.hurtOrSimulate(Entity.java:2386) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1304) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2656) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$3.onAttack(ServerGamePacketListenerImpl.java:2969) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:29) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:89) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2877) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:76) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:14) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1579) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1556) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1549) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:138) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1500) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1510) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1346) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:341) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### CombatLogX Version

[18:32:07 INFO]: Java Version: 21.0.5
[18:32:07 INFO]: Java Vendor: Eclipse Adoptium
[18:32:07 INFO]: Java URL: N/A
[18:32:07 INFO]: Server Version: 1.21.4-15-bb76819 (MC: 1.21.4)
[18:32:07 INFO]: Bukkit Version: 1.21.4-R0.1-SNAPSHOT
[18:32:07 INFO]: Minecraft Version: 1.21.4
[18:32:07 INFO]: NMS Version: Unsupported
[18:32:07 INFO]: Dependency Information:
[18:32:07 INFO]:  - AngelChest v13.9.0
[18:32:07 INFO]:  - CMI v9.7.8.1
[18:32:07 INFO]:  - PlaceholderAPI v2.11.6
[18:32:07 INFO]:  - BlueSlimeCore v2.9.6.431
[18:32:07 INFO]: CombatLogX by SirBlobman
[18:32:07 INFO]: Local Version: 11.5.0.0.1242
[18:32:07 INFO]: Remote Version: 11.5.0.0.1242
[18:32:07 INFO]: Enabled Expansions (6):
[18:32:07 INFO]:  - Action Bar v17.3
[18:32:07 INFO]:  - Boss Bar v17.1
[18:32:07 INFO]:  - Cheat Prevention v17.7
[18:32:07 INFO]:  - AngelChest Compatibility v17.1
[18:32:07 INFO]:  - Mob Tagger v17.1
[18:32:07 INFO]:  - Newbie Helper v17.2

### Anything else?

I'm aware that the plugin has not officially updated to 1.21.4 but feel that it would support it one day anyway.

**Comment by Olivoz** [comment] 2024-12-19 17:35
Duplicate of #837

**Closed** 2024-12-19 19:07 UTC
Labels: Bug
