### ISSUE TITLE
Plugin shows issue when no of players are high

### ISSUE THREAD

**Issue by Cyberlord24** [SirBlobman/CombatLogX#752] opened 2023-12-09 09:23 UTC
### Server Implementation

Spigot

### Server Version

1.20.1

### Describe the bug

In my Minecraft server when there is a rush in the server like when the no of players playing in the smp cross 30-40 players the plugin starts to show issue like the punishment not working or the plugin stops to work. Can u pls help me with this how can I fix this in my server

### Reproduction Steps

.

### Expected behaviour

I wanna know how can I fix that issue so the when there are many people in the serve the plugin doesn't show issue 

### CombatLogX Version

11.4.0.1.1193

**Comment by Olivoz** [comment] 2023-12-12 12:05
Please follow the issue template and provide the output from `/clx version`.
Your issue is probably caused by low TPS and the [minimum-tps](https://github.com/SirBlobman/CombatLogX/blob/ba8af282def020460f9758cd366e59e3374c08b3/plugin/src/main/resources/config.yml#L124) setting in the config.yml

**Comment by SirBlobman** [comment] 2023-12-26 21:01
Closing due to no replies. Please reopen the issue if its still occurring after attempting the fix provided by Olivoz.

**Closed by SirBlobman** 2023-12-26 21:01 UTC
Labels: Bug
