### ISSUE TITLE
Compatibility with MarriageMaster

### ISSUE THREAD

**Issue by thiagogebrimm** [SirBlobman/CombatLogX#330] opened 2021-12-10 02:20 UTC
### Server Implementation

Paper

### Server Version

1.17.1

### CombatLogX Version

[23:18:53 INFO]: Java Version: 16.0.2
[23:18:53 INFO]: Java Vendor: Oracle Corporation
[23:18:53 INFO]: 
[23:18:53 INFO]: Server Version: git-Purpur-1428 (MC: 1.17.1)
[23:18:53 INFO]: Bukkit Version: 1.17.1-R0.1-SNAPSHOT
[23:18:53 INFO]: Minecraft Version: 1.17.1
[23:18:53 INFO]: NMS Version: 1_17_R1
[23:18:53 INFO]: 
[23:18:53 INFO]: Dependency Information:
[23:18:53 INFO]:  - SirBlobmanCore v2.3.3
[23:18:53 INFO]:  - Citizens v2.0.29-SNAPSHOT (build 2416)
[23:18:53 INFO]:  - Essentials v2.19.1-dev+52-41861a8
[23:18:53 INFO]:  - GriefPrevention va8f1743
[23:18:53 INFO]:  - PlaceholderAPI v2.10.10-DEV-139
[23:18:53 INFO]:  - ProtocolLib v4.8.0-SNAPSHOT-b538
[23:18:53 INFO]:  - WorldGuard v7.0.7-SNAPSHOT+2165-81750e1
[23:18:53 INFO]: 
[23:18:53 INFO]: CombatLogX by SirBlobman
[23:18:53 INFO]: Plugin Version: 11.0.0.0-Beta-711
[23:18:53 INFO]: Spigot Version: 10.4.2.4
[23:18:53 INFO]: 
[23:18:53 INFO]: Enabled Expansions (7):
[23:18:53 INFO]:  - ActionBar
[23:18:53 INFO]:  - CheatPrevention
[23:18:53 INFO]:  - CompatEssentialsX
[23:18:53 INFO]:  - CompatGriefPrevention
[23:18:53 INFO]:  - CompatPlaceholderAPI
[23:18:53 INFO]:  - CompatWorldGuard
[23:18:53 INFO]:  - Logger
[23:18:53 INFO]: 

### Plugin

MarriageMaster

### Explanation

To block other players from giving /marry tp during partner combat

**Comment by SirBlobman** [comment] 2021-12-10 13:09
Duplicate of #315

**Closed by SirBlobman** 2021-12-10 13:09 UTC
Labels: Feature Request
